plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/damarff/.hermes/miniapp"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "ALLOWALL"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://telegram.org; style-src 'self' 'unsafe-inline'; connect-src *; img-src * data: blob:; font-src 'self'; frame-ancestors *; base-uri 'self'; form-action 'self';"